see if running pip install mkdocs is necessary for the later scan command to execute correctly

diff --git a/.github/workflows/deployment framework.yml b/.github/workflows/deployment framework.yml
--- a/.github/workflows/deployment framework.yml
+++ b/.github/workflows/deployment framework.yml
@@ -57,13 +57,20 @@ jobs:
           repository: bigsilver07/my-mkdocs-site
           tags: latest, ${{ github.run_number }}
 
+      - name: Install MkDocs and Material Theme
+        run: |
+            pip install mkdocs
+            pip install mkdocs-material
+            
       - name: Lint YAML
         run: yamllint mkdocs.yml
 
-      - name: Scan mkdocs configuration
+      - name: Verify Scan Tool
+        run: which scan || echo "Scan command not found in PATH"
+
+      - name: Run Scan
         run: scan --config-file=mkdocs.yml --strict
         
-         
       - name: Run Link Checker
         env:
           WEBSITE_URL: https://amazing-pudding-ee3b09.netlify.app/
