first attempt at link checker bash script action

diff --git a/.github/workflows/deployment framework.yml b/.github/workflows/deployment framework.yml
--- a/.github/workflows/deployment framework.yml
+++ b/.github/workflows/deployment framework.yml
@@ -56,12 +56,53 @@ jobs:
           password: ${{secrets.DOCKER_PASSWORD}}
           repository: bigsilver07/my-mkdocs-site
           tags: latest, ${{ github.run_number }}
-          
-      - name: Check for broken links
-        run: | 
-          curl -L http://localhost:8000/mysite/
          
+      - name: Run Link Checker
+        env:
+          WEBSITE_URL: http://localhost:8000/mysite/
+        run: |
+          #!/bin/bash
 
+          check_link() {
+          local url = $1
+          http_code=$(curl -o /dev/null --silent --head --write-out '%{http_code} \n' "$url")
+          if [ "http_code" -eq 200]; then
+            echo "ok - $url"
+          else
+            echo "Broken Link ($http_code) - $url"
+            exit 1 # fail the workflow for the presence of defective url's 
+          fi 
+          }
+          
+          #check if URL is provided
+          if [-z "$WEBSITE_URL"]; then 
+          echo "WEBSITE_URL environment variable is not set. "
+          exit 1
+          fi 
+
+          #fetch all href links from our website
+          links=$(curl -s "$WEBSITE_URL" | grep -oP '(?<href=")[^]*')
+
+          #loop through each link, checking their status
+          for link in $links; do
+            # handle relative links by prepending the base URL
+            if [[ "$link" =~ ^/ ]]; then 
+              # Append the relative path to the /mysite/ base URL 
+              if [[ ! "$link" =~ /$ ]]; then 
+                link="WEBSITE_URL${link#/}/"
+              else
+                link = "WEBSITE_URL${link#/}"
+              fi
+            fi
+
+            # skipping internal anchors
+            if [[ ! "$link" = "#" ]]; then 
+              check_link "$link"
+            fi 
+          done
+
+          
+          
           
           
 
